### ISSUE TITLE
Post file user authentication

### ISSUE THREAD

**Issue by Piotrek605** [ncsa/clowder#1]
I'm using RabbitMQ to retrieve files from Clowder and post result files back to the dataset that they came from. I'd like to do that for multiple users, can I somehow upload a file back onto Clowder without providing a specific user's credentials? Or is there a way to get some kind of an authorization key along with the file coming from Clowder?

**Comment by robkooper** [comment]
Each message comes with a key, this key can be used to post a file back into clowder. The file at that point is owned by the "system user".  We are looking at a way to provide a key that is passed in as part of the message that is specific for the user that uploaded the file.

**Comment by lmarini** [comment]
Hi @Piotrek605 this pull request might be of interest to you. It implements API keys by user.

https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests/1175/overview

**Comment by lmarini** [comment]
@Piotrek605 this is now in develop. Can this issue be closed? Thank you.
