### ISSUE TITLE
Message mime type not conforming to standards

### ISSUE THREAD

**Issue by borice** [ncsa/clowder#12]
https://github.com/ncsa/clowder/blob/bb9772d78071732e7321290a017963e2115f18fb/app/services/RabbitmqPlugin.scala#L870
https://github.com/ncsa/clowder/blob/bb9772d78071732e7321290a017963e2115f18fb/app/services/RabbitmqPlugin.scala#L958
https://github.com/ncsa/clowder/blob/bb9772d78071732e7321290a017963e2115f18fb/app/services/RabbitmqPlugin.scala#L1084

Should be `application/json`, not `application\json`.

**Comment by robkooper** [comment]
Pull request has been created see https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/pull-requests/1365/overview (will require login).

**Comment by robkooper** [comment]
fixed in 1.6.2 of clowder (soon to be released).
