### ISSUE TITLE
Clowder behind reverse proxy

### ISSUE THREAD

**Issue by ocaisa** [ncsa/clowder#4]
We are serving Clowder behind a reverse proxy and for the most part that works perfectly fine. The one problem is that the "Add files" page doesn't seem to respect this once a file has been uploaded. The file link it provides is http, which means the user gets sent back to the login page (since they logged in over https). Hopefully the attached picture makes it clear what the problem is. I think if the link provided was relative rather than absolute this would work fine.
![inkedscreenshot 2017-12-21 09 26 58_li](https://user-images.githubusercontent.com/3840437/34247680-ac964b96-e633-11e7-8324-ce99f09cafbd.jpg)

**Comment by robkooper** [comment]
Thanks @ocaisa I'll try to look after new years.

**Comment by ocaisa** [comment]
Thanks for getting back, `securesocial.ssl=true` we have but I don't control the proxy, I'll forward your configuration to the admin and cross-check it. If you can't reproduce then I think this is ok to close as a configuration issue on our side.
