### ISSUE TITLE
Allowing datasets/collections to appear in multiple  spaces

### ISSUE THREAD

**Issue by ocaisa** [ncsa/clowder#7]
The UI currently does not allow adding a collection/dataset to a second space once a first has been added, however if I hack the page to unhide the necessary widget:
```
<div class="row bottom-padding hidden" id="add-to-space-widget">
```
it seems to work perfectly fine. 

Is there a setting to enable this behaviour in general...or a good reason I shouldn't do it?

**Comment by indiragp** [comment]
This is managed through a plugin. In your custom/play.plugins you can add #10900:services.SpaceSharingPlugin 
And that will allow you to have the datasets/collections in more than one space

**Comment by ocaisa** [comment]
Great, thanks @indiragp, works like a charm!
