### ISSUE TITLE
Key appearing in bad URLs

### ISSUE THREAD

**Issue by ocaisa** [ncsa/clowder#8]
I've recently seen a few errors like
```
StatusMessage.error: standard error : 400 Client Error: Bad Request for url: http://AAA.BBB.CCC/api/files/5b4efa0be4b0d62a750ae64c/previews/5b4f29e1e4b0d62a750af4f6?key=XXXXXXX
```
I'm not worried about the error itself, Clowder recovers fine from that, but I was wondering how bad it is that the `commKey` is being exposed? The failure is reported in the extraction events for the dataset so depending on the dataset  permissions, could be world readable.

**Comment by lmarini** [comment]
Thank you @ocaisa for filing this issue. A fix has been merged into master and included in v1.4.2 release. https://github.com/ncsa/clowder/blob/master/CHANGELOG.md
